spring:
  application:
    name: task-manager-app
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true